import Head from "next/head";
import { ReactNode } from "react";
import Footer from "./footer";
import Navbar from "./navbar";

type LayoutProps = {
	children: ReactNode;
};

const Layout = ({ children }: LayoutProps) => {
	return (
		<>
			<Head>
				<title>
					Giza - Permisionless Decentralized Freelancing Marketplace
				</title>
				<meta
					name="Gigza"
					content="Gigza is a permisionless decentralized freelancing marketplace that allows anyone to post a job and get help from freelancers with the requisite skills."
				/>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Navbar />
			<main className="mt:h-20 mt-[62px]">{children}</main>
			<Footer />
		</>
	);
};

export default Layout;
